export interface ChecklistStep {
  id: number;
  title: string;
  description: string;
}

export const CHECKLIST_STEPS: ChecklistStep[] = [
  // Section 1: Job Prep
  { id: 1, title: 'Schedule the Job', description: 'To Schedule the Job:\n- Ensure job is added to [Field Team Spreadsheet](https://docs.google.com/spreadsheets/d/1rYt_fyrlUMnSZB97MwX-XVBHNyJSpYeKerGR1GwxE_Y/edit?gid=0#gid=0)\n- Additionally, ensure a google calendar invite has been created with Josue, Zack, Robert, and Daniel that includes Site Contact Info, and Price\n- Put any images or information from client into the main company folder under a [subfolder](https://drive.google.com/drive/u/3/folders/11n1EzrSNTScBCjyhzE0W6m82PlxIa2L3) for the individual project' },
  { id: 2, title: 'Collect Site Materials and Site Contact Information', description: 'You have now scheduled the project but need more information before getting started on the project. Chat with the client who you scheduled the project with:\n- Ask if any plans exist ("Do you have any as-builts, utility plans, or site drawings for this project?")\n- Clarify what types of plans help the most ("Civil plans, utility composites, water/sewer/storm layouts, electrical, comms, or any previous locating maps all help us make sure nothing gets missed")\n- Explain why they matter ("These give us a better idea of what to expect underground so we can be as accurate as possible")\n- Request preferred file types ("PDFs are perfect, but CAD files work too if you have them")\n- Confirm how they will send them ("Email, shared link, google drive, printed copy onsite, etc.")\n- Request onsite contact information ("Who should we call or check in with when we arrive tomorrow? A name and phone number helps us get on site quickly")\n- Add all information given onto calendar ("All information given from client is to be added onto google calendar for quick access")' },
  { id: 3, title: 'Create Job Ticket', description: 'Now you need to create the job ticket in the ASC Web App:\n- Open up the [ASC Web App](https://app.advancedspadecompany.com/orgs/demo-org)\n- Select "Tickets" tab\n- Select "Create New Ticket"\n- Ticket generating information:\n  - Ticket name should be Company_City_Street Address, matching field team schedule and calendar\n  - Skip the invoice number section\n  - Label priority appropriately\n  - Label the status to match project milestone\n  - Assign to the field tech who will complete the project\n  - Add any associated user who needs to be notified of status\n  - Add project start date, deliverable due date, customer name, address, and any additional notes\n- Select "Create"\n- Attach project related documentation:\n  - Select "Surveys" tab\n  - Click "Create New Survey"\n  - Fill out new survey tab options by leaving utility type blank\n  - Put the identical survey name as the ticket name with a title change only at the end (include - Site Photos)\n  - Leave device option blank\n  - Insert surveyor name\n  - Upload data accordingly (PDFs or images)\n  - Select "Create Survey"\n  - Select "Save"\n  - Attach survey to ticket by selecting the ticket and "Attach Survey Data"\n  - Find the survey from the list\n  - Select "Attach" and "Save Surveys"\n- Ticket is now created with attachments\n- Share ticket information on google calendar for easy access' },
  { id: 4, title: 'Airspace Clearance Request/Confirmation', description: 'Verify we have proper drone clearance and permissions for the site. This is REQUIRED before every drone flight.\n\n- Check weather conditions:\n  - Check weather on phone app\n  - Look outside for signs of possible rain\n  - Ideal wind < 8 m/s\n  - No heavy rain\n  - Good visibility\n\n- Verify local airspace requirements & geofencing clearance using [Airspace Link](https://airspacelink.com)\n  - After signing in, click the "+" icon at the top right corner to create an airspace request\n\n- Section 1 - Enter operation details:\n  - Name of the operation\n  - Description of the operation\n  - Select: "Commercial - Part 107"\n\n- Section 2 - Define flight area:\n  - Draw the planned area of excavation (circle, square, or free form polygon)\n  - Enter max altitude of planned flight (cannot exceed the altitude of the grids)\n  - Note: If higher altitude needed, wait minimum 72 hours for response\n\n- Section 3 - Schedule the operation:\n  - Start Date and Time\n  - Planned duration of the operation\n  - The time zone of the operation\n  - Click "Save Operation" to go to confirmation page\n\n- Confirm and submit:\n  - Review all details of the operation\n  - Click "Get LAANC"\n  - Enter your email and phone number\n  - Click "Confirm"\n  - Click "Submit Request" to submit the airspace request\n  - You now have a valid airspace request for your operation\n\n- Notes about restricted airspace areas:\n  - Any grid that is not red or not 0 can be flown in at any time once the request notification is submitted\n  - Yellow 0 zones are typically approved up to a low altitude (50-100 ft depending on location) with a required minimum 72 hour notice\n  - Red zones, regardless of altitude listed, require permission to be filed through FAA drone zone\n  - If you are unsure, ask Charles Folashade to fill this out for you' },
  { id: 5, title: 'Complete Equipment Pre-Check', description: 'Before heading to the site:\n -Make sure you have all [Field Equipment](https://aspadeco.atlassian.net/wiki/spaces/ASC/pages/170819597/Field+Equipment+Checklist) and [Safety Equipment](https://aspadeco.atlassian.net/wiki/spaces/ASC/pages/170164229/Safety+PPE)\n -Power on your equipment to confirm it is charged, working, and ready to use\n -Verify everything is loaded in the truck so nothing gets left behind' },
  { id: 6, title:  'Confirm Job with Client (refer to step 1)', description: 'To confirm your client job:\n- Review job details (date, time, scope)\n- Contact client to confirm (phone call or text confirming time and address)\n- Verify site access (ask if gate codes, escorts, or special instructions are needed)\n- Confirm traffic control (make sure TC is still scheduled or handled by client)\n- Send confirmation to internal team if any changes occur through slack channel'},

  // Section 2: Field Operations
  { id: 7, title: 'Final Equipment Check', description: '' },
  { id: 8, title: 'Communicate with Client', description: '' },
  { id: 9, title: 'Site Walk', description: '' },
  { id: 10, title: 'EM Locate', description: '' },
  { id: 11, title: 'GPR', description: '' },
  { id: 12, title: 'Rodder', description: '' },
  { id: 13, title: 'Site Photography', description: '' },
  { id: 14, title: 'Emlid', description: '' },
  { id: 15, title: 'Drone', description: '' },
  { id: 16, title: 'Site Departure', description: '' },

  // Section 3: Office Work
  { id: 17, title: 'Upload Emlid', description: 'Upload and process Emlid GPS data' },
  { id: 18, title: 'Process Drone Map', description: 'Upload and process drone footage and imagery' },
  { id: 19, title: 'Close Report', description: 'Complete and finalize the comprehensive site report' },
  { id: 20, title: 'Deliverables Submitted', description: 'Publish and deliver report to client' },
  { id: 21, title: 'Invoice Job', description: 'Generate and send invoice for completed work' },
];

